//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cambio_Asiento
    {
        public int ID_Cambio { get; set; }
        public System.DateTime Fecha_Hora_Cambio { get; set; }
        public int ID_Transaccion { get; set; }
        public int ID_AsientoTransaccion { get; set; }
    
        public virtual Transaccion_Asiento Transaccion_Asiento { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
