//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Transaccion
    {
        public int ID_Log { get; set; }
        public System.DateTime Fecha_Hora { get; set; }
        public string Usuario { get; set; }
        public string Accion { get; set; }
        public int ID_Operacion { get; set; }
        public string Tabla_Cambio { get; set; }
        public string Datos_Anteriores { get; set; }
        public string Datos_Nuevos { get; set; }
        public string Descripcion { get; set; }
    }
}
