//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CINEBDEntities1 : DbContext
    {
        public CINEBDEntities1()
            : base("name=CINEBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Cambio_Asiento> Cambio_Asiento { get; set; }
        public virtual DbSet<Catalogo_Asignacion> Catalogo_Asignacion { get; set; }
        public virtual DbSet<Log_Transaccion> Log_Transaccion { get; set; }
        public virtual DbSet<Pelicula> Pelicula { get; set; }
        public virtual DbSet<SALA> SALA { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<SesionCSV> SesionCSV { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
        public virtual DbSet<Transaccion_Asiento> Transaccion_Asiento { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
