//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sesion()
        {
            this.Transaccion_Asiento = new HashSet<Transaccion_Asiento>();
        }
    
        public int ID_Sesion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public string Estado { get; set; }
        public bool OrigenCSV { get; set; }
        public Nullable<int> GrupoCSV { get; set; }
        public int ID_Sala { get; set; }
        public int ID_Pelicula { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual SALA SALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Asiento> Transaccion_Asiento { get; set; }
    }
}
