//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion_Asiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion_Asiento()
        {
            this.Cambio_Asiento = new HashSet<Cambio_Asiento>();
        }
    
        public int ID_AsientoTransaccion { get; set; }
        public string Estado_Asignacion { get; set; }
        public System.DateTime Fecha_Hora_Asignacion { get; set; }
        public int ID_Transaccion { get; set; }
        public int ID_Asiento { get; set; }
        public int ID_Sesion { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cambio_Asiento> Cambio_Asiento { get; set; }
        public virtual Sesion Sesion { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
