//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CINEGT2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Cambio_Asiento = new HashSet<Cambio_Asiento>();
            this.Transaccion_Asiento = new HashSet<Transaccion_Asiento>();
        }
    
        public int ID_Transaccion { get; set; }
        public System.DateTime Fecha_Hora { get; set; }
        public string Tipo_Transaccion { get; set; }
        public int Cantidad_Asientos { get; set; }
        public string Estado { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Tipo_Asignacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cambio_Asiento> Cambio_Asiento { get; set; }
        public virtual Catalogo_Asignacion Catalogo_Asignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion_Asiento> Transaccion_Asiento { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
